# English subgraph

CONSTRUCT {

?Subject xl:prefLabel ?prefLabel ;
         xl:altLabel ?altLabel ;
         skos:scopeNote ?scopeNote .

?prefLabel xl:literalForm ?prefLabel_lit ;
           rdfs:comment ?prefLabel_comment .

?altLabel xl:literalForm ?altLabel_lit ;
          rdfs:comment ?altLabel_comment .

?scopeNote rdf:value ?scopeNote_lit .

}

WHERE {

  ?Subject a gvp:Concept ;
          xl:prefLabel ?prefLabel .
  ?prefLabel xl:literalForm ?prefLabel_lit ;
             dcterms:language aat:300388277 .

  OPTIONAL { ?Subject xl:altLabel ?altLabel .
             ?altLabel xl:literalForm ?altLabel_lit ;
                       dcterms:language aat:300388277 .
             OPTIONAL { ?altLabel rdfs:comment ?altLabel_comment . } 
           }

  OPTIONAL { ?prefLabel rdfs:comment ?prefLabel_comment . }

  OPTIONAL { ?Subject skos:scopeNote ?scopeNote .
             ?scopeNote rdf:value ?scopeNote_lit ;
                        dcterms:language aat:300388277 . }

}

# Dutch subgraph

CONSTRUCT {

?Subject xl:prefLabel ?prefLabel ;
         xl:altLabel ?altLabel ;
         skos:scopeNote ?scopeNote .

?prefLabel xl:literalForm ?prefLabel_lit ;
           rdfs:comment ?prefLabel_comment .

?altLabel xl:literalForm ?altLabel_lit ;
          rdfs:comment ?altLabel_comment .

?scopeNote rdf:value ?scopeNote_lit .

}

WHERE {

  ?Subject a gvp:Concept ;
          xl:prefLabel ?prefLabel .
  ?prefLabel xl:literalForm ?prefLabel_lit ;
             dcterms:language aat:300388256 .

  OPTIONAL { ?Subject xl:altLabel ?altLabel .
             ?altLabel xl:literalForm ?altLabel_lit ;
                       dcterms:language aat:300388256 .
             OPTIONAL { ?altLabel rdfs:comment ?altLabel_comment . } 
           }

  OPTIONAL { ?prefLabel rdfs:comment ?prefLabel_comment . }

  OPTIONAL { ?Subject skos:scopeNote ?scopeNote .
             ?scopeNote rdf:value ?scopeNote_lit ;
                        dcterms:language aat:300388256 . }

}